---
- name: zips files older than 90 days
  hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Zip /var/log
    command: "find /var/log/httpd/ -type f -name *.log -mtime +15 -exec gzip.* -9 {} \ ; "
