---
- name: Helps to doawnload file
  hosts: localhost
  become: yes
  become_method: sudo
  vars_prompt: 
  - name: URL
    promt: "Give me the url:"
    private: no
  - name: Destination
    prompt: "Give me the location to put:"
   private: no
tasks: 
  - name: Download 1 Package
    get_url:
      url: "{{URL}}"
      dest: /tmp/
        