---
- name: take an image of instance
  hosts: all
  become: yes
  become_user: root
- ec2_ami:
    instance_id: "{{i-xxxxxx}}"
    wait: yes
    name: newtest
    # tags:
    #   Name: newtest
    #   Service: TestService