--- 
- name: Terminate instances
  hosts: localhost
  tasks:
   - name: terminate instances
     ec2: 
       instance_ids: "{{ instance_id }}"
       state: "{{state}}" #stopped  #started  #restarted
       region: "{{region}}"
